#Config Information for LifestealSMP by HadesDC
#This is your basic configureation for the LifestealSMP plugin


###############################################################
##### Database Settings! THEESE ARE A MUST
###############################################################
Mysql:
  Enabled: true
  Host: 'localhost'
  Port: 3306
  Database: 'lifestealsmp'
  Username: 'root'
  Password: ''